export interface CurrencyInfo {
  code: string;
  symbol: string;
}

const countryToCurrency: Record<string, CurrencyInfo> = {
  // African Nations
  "ghana": { code: "GHS", symbol: "GH₵" },
  "nigeria": { code: "NGN", symbol: "₦" },
  "kenya": { code: "KES", symbol: "KSh" },
  "south africa": { code: "ZAR", symbol: "R" },
  "uganda": { code: "UGX", symbol: "USh" },
  "tanzania": { code: "TZS", symbol: "TSh" },
  "zambia": { code: "ZMW", symbol: "ZK" },
  "cameroon": { code: "XAF", symbol: "FCFA" },
  "ivory coast": { code: "XOF", symbol: "CFA" },
  "cote d'ivoire": { code: "XOF", symbol: "CFA" },
  "senegal": { code: "XOF", symbol: "CFA" },
  "mali": { code: "XOF", symbol: "CFA" },
  "burkina faso": { code: "XOF", symbol: "CFA" },
  "benin": { code: "XOF", symbol: "CFA" },
  "togo": { code: "XOF", symbol: "CFA" },
  "niger": { code: "XOF", symbol: "CFA" },
  "gabon": { code: "XAF", symbol: "FCFA" },
  "congo": { code: "XAF", symbol: "FCFA" },
  "congo, democratic republic of the": { code: "CDF", symbol: "FC" },
  "democratic republic of the congo": { code: "CDF", symbol: "FC" },
  "chad": { code: "XAF", symbol: "FCFA" },
  "central african republic": { code: "XAF", symbol: "FCFA" },
  "equatorial guinea": { code: "XAF", symbol: "FCFA" },
  "liberia": { code: "LRD", symbol: "$" },
  "sierra leone": { code: "SLE", symbol: "Le" },
  "gambia": { code: "GMD", symbol: "D" },
  "rwanda": { code: "RWF", symbol: "FRw" },
  "burundi": { code: "BIF", symbol: "FBu" },
  "ethiopia": { code: "ETB", symbol: "Br" },
  "malawi": { code: "MWK", symbol: "MK" },
  "zimbabwe": { code: "ZWL", symbol: "$" },
  "botswana": { code: "BWP", symbol: "P" },
  "namibia": { code: "NAD", symbol: "$" },
  "egypt": { code: "EGP", symbol: "E£" },
  "morocco": { code: "MAD", symbol: "DH" },

  // Americas
  "united states": { code: "USD", symbol: "$" },
  "usa": { code: "USD", symbol: "$" },
  "canada": { code: "CAD", symbol: "$" },
  "mexico": { code: "MXN", symbol: "$" },
  "brazil": { code: "BRL", symbol: "R$" },
  "colombia": { code: "COP", symbol: "$" },
  "argentina": { code: "ARS", symbol: "$" },
  "chile": { code: "CLP", symbol: "$" },
  "peru": { code: "PEN", symbol: "S/" },

  // Europe
  "united kingdom": { code: "GBP", symbol: "£" },
  "uk": { code: "GBP", symbol: "£" },
  "spain": { code: "EUR", symbol: "€" },
  "france": { code: "EUR", symbol: "€" },
  "germany": { code: "EUR", symbol: "€" },
  "italy": { code: "EUR", symbol: "€" },
  "netherlands": { code: "EUR", symbol: "€" },
  "ireland": { code: "EUR", symbol: "€" },
  "portugal": { code: "EUR", symbol: "€" },
  "belgium": { code: "EUR", symbol: "€" },
  "austria": { code: "EUR", symbol: "€" },
  "switzerland": { code: "CHF", symbol: "CHF" },
  "sweden": { code: "SEK", symbol: "kr" },
  "norway": { code: "NOK", symbol: "kr" },
  "denmark": { code: "DKK", symbol: "kr" },
  "poland": { code: "PLN", symbol: "zł" },
  "russia": { code: "RUB", symbol: "₽" },

  // Asia & Pacific
  "china": { code: "CNY", symbol: "¥" },
  "japan": { code: "JPY", symbol: "¥" },
  "south korea": { code: "KRW", symbol: "₩" },
  "korea, south": { code: "KRW", symbol: "₩" },
  "india": { code: "INR", symbol: "₹" },
  "philippines": { code: "PHP", symbol: "₱" },
  "vietnam": { code: "VND", symbol: "₫" },
  "thailand": { code: "THB", symbol: "฿" },
  "indonesia": { code: "IDR", symbol: "Rp" },
  "malaysia": { code: "MYR", symbol: "RM" },
  "singapore": { code: "SGD", symbol: "$" },
  "pakistan": { code: "PKR", symbol: "Rs" },
  "bangladesh": { code: "BDT", symbol: "৳" },
  "sri lanka": { code: "LKR", symbol: "Rs" },
  "nepal": { code: "NPR", symbol: "Rs" },
  "australia": { code: "AUD", symbol: "$" },
  "new zealand": { code: "NZD", symbol: "$" },
  "papua new guinea": { code: "PGK", symbol: "K" },
};

export const SUPPORTED_COUNTRIES: string[] = [
  "Argentina",
  "Australia",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Benin",
  "Botswana",
  "Brazil",
  "Burkina Faso",
  "Burundi",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Democratic Republic of the Congo",
  "Denmark",
  "Egypt",
  "Equatorial Guinea",
  "Ethiopia",
  "France",
  "Gabon",
  "Gambia",
  "Germany",
  "Ghana",
  "India",
  "Indonesia",
  "Ireland",
  "Italy",
  "Ivory Coast",
  "Japan",
  "Kenya",
  "Liberia",
  "Malawi",
  "Malaysia",
  "Mali",
  "Mexico",
  "Morocco",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Niger",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Papua New Guinea",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Russia",
  "Rwanda",
  "Senegal",
  "Sierra Leone",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Tanzania",
  "Thailand",
  "Togo",
  "Uganda",
  "United Kingdom",
  "United States",
  "Vietnam",
  "Zambia",
  "Zimbabwe"
].sort();

export function getNormalizedCountryName(countryName: string): string {
  if (!countryName) return "";
  const trimmed = countryName.trim();
  const found = SUPPORTED_COUNTRIES.find(c => c.toLowerCase() === trimmed.toLowerCase());
  return found || trimmed;
}

export function getCurrencyByCountry(country: string): CurrencyInfo {
  const normalized = country.trim().toLowerCase();
  return countryToCurrency[normalized] || { code: "USD", symbol: "$" };
}
