export interface DefaultIngredientInput {
  name: string;
  mainCategory: string;
  crudeProtein: number;
  crudeFiber: number;
  calcium: number;
  phosphorus: number;
  sodium: number;
  chloride: number;
  potassium: number;
  sulfur: number;
  metabolizableEnergy: number;
  dryMatter: number;
  fat: number;
  lysine: number;
  methionine: number;
  cystine: number;
  threonine: number;
  tryptophan: number;
  arginine: number;
  isoleucine: number;
  valine: number;
  maxStarter: number;
  maxGrower: number;
  maxFinisher: number;
  costPerKg: number;
  quantity: number;
  unit: string;
  visible: boolean;
  description: string;
}

export const defaultIngredients: DefaultIngredientInput[] = [
  // ENERGY SOURCES
  {
    name: "Maize",
    mainCategory: "Energy",
    crudeProtein: 8.0,
    crudeFiber: 2.4,
    calcium: 0.04,
    phosphorus: 0.29,
    sodium: 0.05,
    chloride: 0.0,
    potassium: 0.36,
    sulfur: 0.0,
    metabolizableEnergy: 18.8 * 239,
    dryMatter: 86.3,
    fat: 3.8,
    lysine: 2.9,
    methionine: 1.7,
    cystine: 2.1,
    threonine: 4.2,
    tryptophan: 1.8,
    arginine: 6.6,
    isoleucine: 4.0,
    valine: 5.3,
    maxStarter: 70.0,
    maxGrower: 65.0,
    maxFinisher: 30.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Primary energy source from yellow/white dent maize."
  },
  {
    name: "Wheat bran",
    mainCategory: "Energy",
    crudeProtein: 17.3,
    crudeFiber: 10.4,
    calcium: 0.14,
    phosphorus: 1.11,
    sodium: 0.03,
    chloride: 0.0,
    potassium: 1.37,
    sulfur: 0.0,
    metabolizableEnergy: 18.9 * 239,
    dryMatter: 87.0,
    fat: 4.2,
    lysine: 4.0,
    methionine: 1.5,
    cystine: 2.1,
    threonine: 3.2,
    tryptophan: 1.4,
    arginine: 6.8,
    isoleucine: 3.2,
    valine: 4.6,
    maxStarter: 10.0,
    maxGrower: 20.0,
    maxFinisher: 30.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Fibrous wheat processing byproduct."
  },
  {
    name: "Maize bran",
    mainCategory: "Energy",
    crudeProtein: 11.0,
    crudeFiber: 12.3,
    calcium: 0.47,
    phosphorus: 0.34,
    sodium: 0.08,
    chloride: 0.0,
    potassium: 0.73,
    sulfur: 0.0,
    metabolizableEnergy: 18.5 * 239,
    dryMatter: 88.7,
    fat: 5.0,
    lysine: 4.2,
    methionine: 1.8,
    cystine: 2.1,
    threonine: 4.0,
    tryptophan: 1.1,
    arginine: 5.2,
    isoleucine: 3.3,
    valine: 5.1,
    maxStarter: 20.0,
    maxGrower: 30.0,
    maxFinisher: 35.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Byproduct from wet or dry maize milling."
  },
  {
    name: "Rice bran",
    mainCategory: "Energy",
    crudeProtein: 12.7,
    crudeFiber: 16.3,
    calcium: 0.07,
    phosphorus: 1.38,
    sodium: 0.02,
    chloride: 0.0,
    potassium: 1.23,
    sulfur: 0.0,
    metabolizableEnergy: 20.5 * 239,
    dryMatter: 90.0,
    fat: 14.0,
    lysine: 4.4,
    methionine: 1.9,
    cystine: 1.7,
    threonine: 3.7,
    tryptophan: 2.2,
    arginine: 7.2,
    isoleucine: 5.3,
    valine: 5.4,
    maxStarter: 10.0,
    maxGrower: 20.0,
    maxFinisher: 30.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Rice milling byproduct, rich in fats and B vitamins."
  },

  // PROTEIN SOURCES
  {
    name: "Soybean meal",
    mainCategory: "Protein",
    crudeProtein: 49.5,
    crudeFiber: 7.2,
    calcium: 0.39,
    phosphorus: 0.71,
    sodium: 0.0,
    chloride: 0.01,
    potassium: 2.45,
    sulfur: 0.45,
    metabolizableEnergy: 21.1 * 239,
    dryMatter: 93.2,
    fat: 1.5,
    lysine: 6.2,
    methionine: 1.4,
    cystine: 1.5,
    threonine: 3.9,
    tryptophan: 1.4,
    arginine: 7.3,
    isoleucine: 4.6,
    valine: 4.8,
    maxStarter: 20.0,
    maxGrower: 35.0,
    maxFinisher: 15.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "High-quality solvent extracted soybean meal."
  },
  {
    name: "Fish meal",
    mainCategory: "Protein",
    crudeProtein: 70.6,
    crudeFiber: 1.0,
    calcium: 4.34,
    phosphorus: 2.79,
    sodium: 1.13,
    chloride: 0.0,
    potassium: 0.87,
    sulfur: 0.22,
    metabolizableEnergy: 21.9 * 239,
    dryMatter: 92.1,
    fat: 9.0,
    lysine: 7.5,
    methionine: 2.7,
    cystine: 0.8,
    threonine: 4.1,
    tryptophan: 1.0,
    arginine: 6.2,
    isoleucine: 4.2,
    valine: 4.9,
    maxStarter: 10.0,
    maxGrower: 8.0,
    maxFinisher: 5.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Animal protein source rich in amino acids and minerals."
  },

  // VITAMINS, MINERALS & SALT
  {
    name: "Oyster Shell",
    mainCategory: "Vitamins, Minerals & Salt",
    crudeProtein: 0.0,
    crudeFiber: 0.0,
    calcium: 400.0,
    phosphorus: 3.4,
    sodium: 5.4,
    chloride: 0.0,
    potassium: 0.1,
    sulfur: 0.0,
    metabolizableEnergy: 0.0,
    dryMatter: 92.6,
    fat: 0.0,
    lysine: 0.0,
    methionine: 0.0,
    cystine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    arginine: 0.0,
    isoleucine: 0.0,
    valine: 0.0,
    maxStarter: 5.0,
    maxGrower: 5.0,
    maxFinisher: 5.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Excellent calcium carbonate source for bone structure."
  },
  {
    name: "Bone Meal",
    mainCategory: "Vitamins, Minerals & Salt",
    crudeProtein: 0.0,
    crudeFiber: 0.0,
    calcium: 303.2,
    phosphorus: 140.2,
    sodium: 10.0,
    chloride: 0.0,
    potassium: 0.4,
    sulfur: 0.0,
    metabolizableEnergy: 1.6 * 239,
    dryMatter: 95.4,
    fat: 3.0,
    lysine: 0.0,
    methionine: 0.0,
    cystine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    arginine: 0.0,
    isoleucine: 0.0,
    valine: 0.0,
    maxStarter: 5.0,
    maxGrower: 5.0,
    maxFinisher: 5.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Good source of both calcium and phosphorus."
  },
  {
    name: "Common salt",
    mainCategory: "Vitamins, Minerals & Salt",
    crudeProtein: 0.0,
    crudeFiber: 0.0,
    calcium: 0.0,
    phosphorus: 0.0,
    sodium: 387.0,
    chloride: 0.0,
    potassium: 0.0,
    sulfur: 0.0,
    metabolizableEnergy: 0.0,
    dryMatter: 99.5,
    fat: 0.0,
    lysine: 0.0,
    methionine: 0.0,
    cystine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    arginine: 0.0,
    isoleucine: 0.0,
    valine: 0.0,
    maxStarter: 2.0,
    maxGrower: 2.0,
    maxFinisher: 2.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Source of sodium and chlorine for fluid balance."
  },
  {
    name: "Vitamin Premix",
    mainCategory: "Vitamins, Minerals & Salt",
    crudeProtein: 2.0,
    crudeFiber: 1.0,
    calcium: 0.0,
    phosphorus: 0.0,
    sodium: 0.0,
    chloride: 0.0,
    potassium: 1.0,
    sulfur: 0.0,
    metabolizableEnergy: 4.0 * 239,
    dryMatter: 95.0,
    fat: 1.0,
    lysine: 3.0,
    methionine: 1.2,
    cystine: 1.5,
    threonine: 2.8,
    tryptophan: 1.0,
    arginine: 5.5,
    isoleucine: 0.0,
    valine: 4.0,
    maxStarter: 2.0,
    maxGrower: 2.0,
    maxFinisher: 2.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Essential vitamins and trace minerals blend."
  },
  {
    name: "Mycotoxin Binder",
    mainCategory: "Vitamins, Minerals & Salt",
    crudeProtein: 0.0,
    crudeFiber: 0.0,
    calcium: 0.0,
    phosphorus: 0.0,
    sodium: 0.0,
    chloride: 0.0,
    potassium: 0.0,
    sulfur: 0.0,
    metabolizableEnergy: 0.0,
    dryMatter: 90.0,
    fat: 0.0,
    lysine: 0.0,
    methionine: 0.0,
    cystine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    arginine: 0.0,
    isoleucine: 0.0,
    valine: 0.0,
    maxStarter: 2.0,
    maxGrower: 2.0,
    maxFinisher: 2.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Binds mycotoxins in feed to protect animal health."
  },
  {
    name: "Lysine",
    mainCategory: "Vitamins, Minerals & Salt",
    crudeProtein: 93.0,
    crudeFiber: 0.0,
    calcium: 0.0,
    phosphorus: 0.0,
    sodium: 158.0,
    chloride: 0.0,
    potassium: 0.0,
    sulfur: 0.0,
    metabolizableEnergy: 18.8 * 239,
    dryMatter: 99.0,
    fat: 0.0,
    lysine: 78.8,
    methionine: 0.0,
    cystine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    arginine: 0.0,
    isoleucine: 0.0,
    valine: 0.0,
    maxStarter: 2.0,
    maxGrower: 2.0,
    maxFinisher: 2.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Essential amino acid supplement."
  },
  {
    name: "Methionine",
    mainCategory: "Vitamins, Minerals & Salt",
    crudeProtein: 58.7,
    crudeFiber: 0.0,
    calcium: 0.0,
    phosphorus: 0.0,
    sodium: 0.0,
    chloride: 214.0,
    potassium: 0.0,
    sulfur: 0.0,
    metabolizableEnergy: 21.8 * 239,
    dryMatter: 99.0,
    fat: 0.0,
    lysine: 0.0,
    methionine: 99.0,
    cystine: 0.0,
    threonine: 0.0,
    tryptophan: 0.0,
    arginine: 0.0,
    isoleucine: 0.0,
    valine: 0.0,
    maxStarter: 2.0,
    maxGrower: 2.0,
    maxFinisher: 2.0,
    costPerKg: 0.0,
    quantity: 0.0,
    unit: "kg",
    visible: true,
    description: "Sulfur-containing essential amino acid supplement."
  }
];
