export type SeverityLevel = "LOW" | "MODERATE" | "HIGH" | "CRITICAL";

export type PigStage =
  | "stage_all"
  | "stage_suckling"
  | "stage_nursery"
  | "stage_grower_finisher"
  | "stage_breeding_stock";

export interface PigStageOption {
  key: PigStage;
  labelKey: string;
  label: string;
}

export const PIG_STAGE_OPTIONS: PigStageOption[] = [
  { key: "stage_all", labelKey: "stage_all", label: "All Stages" },
  { key: "stage_suckling", labelKey: "stage_suckling", label: "Suckling (< 4 wks)" },
  { key: "stage_nursery", labelKey: "stage_nursery", label: "Nursery / Weaners (4–10 wks)" },
  { key: "stage_grower_finisher", labelKey: "stage_grower_finisher", label: "Growers / Finishers (10–24 wks)" },
  { key: "stage_breeding_stock", labelKey: "stage_breeding_stock", label: "Breeding Stock (Sows/Boars)" },
];

export function getStageFromPigStatus(status?: string, purpose?: string): PigStage {
  if (!status) return "stage_all";
  const s = status.toUpperCase();
  if (s === "PIGLET") return "stage_suckling";
  if (s === "STARTER") return "stage_nursery";
  if (s === "GROWER" || s === "FINISHER") return "stage_grower_finisher";
  if (
    s === "SOW" || s === "GILT" || s === "BOAR" || s === "BARROW" ||
    s === "PREGNANT" || s === "LACTATING" || s === "NURSING"
  ) {
    return "stage_breeding_stock";
  }
  if (purpose && purpose.toUpperCase() === "BREEDER") return "stage_breeding_stock";
  return "stage_all";
}

export interface DiseaseItem {
  id: string;
  nameKey: string;
  scientificNameKey: string;
  symptomKeys: string[];
  descriptionKey: string;
  severity: SeverityLevel;
  preventionKey: string;
  stages?: PigStage[];
  isNotifiable?: boolean;
  biosecurityProtocolKey?: string;
}

export const SYMPTOM_WEIGHTS: Record<string, number> = {
  // Weight 3.0: Pathognomonic / Hallmark Signs
  sym_diamond_lesions: 3.0,
  sym_blisters_snout_feet: 3.0,
  sym_bleeding_orifices: 3.0,
  sym_nose_bleeds: 3.0,
  sym_mummified_piglets: 3.0,
  sym_rectal_prolapse: 3.0,
  sym_convulsions: 3.0,
  sym_paralysis: 3.0,

  // Weight 2.0: Moderate Specificity
  sym_bloody_diarrhea: 2.0,
  sym_abortion: 2.0,
  sym_thumping: 2.0,
  sym_swollen_joints: 2.0,
  sym_trembling: 2.0,
  sym_seizures: 2.0,
  sym_swollen_eyelids: 2.0,
  sym_jaundice: 2.0,
  sym_ear_necrosis: 2.0,
  sym_skin_crusts: 2.0,
  sym_frothing: 2.0,
  sym_excessive_salivation: 2.0,
  sym_blood_in_stool: 2.0,
  sym_difficulty_breathing: 2.0,
  sym_sudden_death: 2.0,
  sym_watery_diarrhea: 2.0,
  sym_infertility: 2.0,
  sym_enlarged_scrotum: 2.0,
  sym_swollen_udder: 2.0,
  sym_swollen_vulva: 2.0,
  sym_abscesses: 2.0,
  sym_swollen_navel: 2.0,
};

export function getSymptomWeight(key: string): number {
  return SYMPTOM_WEIGHTS[key] || 1.0;
}

export function isPathognomonic(key: string): boolean {
  return getSymptomWeight(key) >= 3.0;
}

export const SYMPTOM_SUBTITLES: Record<string, string> = {
  sym_thumping: "Rapid, jerky abdominal/belly breathing",
  sym_diamond_lesions: "Raised diamond/square red-purple skin plaques",
  sym_blisters_snout_feet: "Fluid-filled sores/vesicles on snout, lips, or hoof band",
  sym_bleeding_orifices: "Dark blood from nostrils, mouth, or rectum",
  sym_nose_bleeds: "Active blood dripping from the snout",
  sym_rectal_prolapse: "Internal pink/red tissue protruding outside the anus",
  sym_skin_discoloration: "Purplish or blue-red patches on ears, belly, or snout",
  sym_incoordination: "Ataxia, wobbly gait, staggering or swaying while walking",
  sym_trembling: "Shaking, shivering, or involuntary body quivers",
  sym_mummified_piglets: "Blackened, shriveled dead piglets born at farrowing",
  sym_swollen_eyelids: "Puffy, swollen eyes (common in Edema disease)",
  sym_jaundice: "Yellowish tint in eyes, mucous membranes, or pale skin",
  sym_ear_necrosis: "Blackening, crusting, or rotting of ear tips",
  sym_convulsions: "Paddling legs, violent uncontrolled body spasms",
  sym_watery_diarrhea: "Profuse liquid yellow/grey scours",
  sym_bloody_diarrhea: "Mucoid red/dark tarry scours",
  sym_stunted_growth: "Runts failing to gain weight alongside pen-mates",
  sym_pale_skin: "Chalky white skin and gums (severe anemia)",
  sym_rough_hair: "Dull, unkempt, bristly coat standing on end",
  sym_muscle_stiffness: "Stiff wooden gait, locked jaws, or arched back (tetanus)",
  sym_circling: "Compulsive walking in circles or tilted head",
  sym_bloat: "Severely distended, tight, swollen belly",
  sym_nasal_discharge: "Mucus, phlegm, or pus dripping from snout",
  sym_excessive_salivation: "Heavy drooling, foaming, or slobbering",
  sym_blindness: "Bumping into pen walls, unreactive pupils",
  sym_swollen_joints: "Enlarged, hot, painful hocks, knees, or feet",
  sym_tail_biting: "Aggressive chewing and bloody wounds on tails",
  sym_cracked_hooves: "Splits, fissures, or deep cracks in hoof walls",
  sym_swollen_navel: "Enlarged, hot, infected umbilical stump",
};

export function getSymptomSubtitle(key: string): string | undefined {
  return SYMPTOM_SUBTITLES[key];
}

export interface SymptomGroup {
  id: string;
  nameKey: string;
  symptoms: string[];
}

export const SYMPTOM_GROUPS: SymptomGroup[] = [
  {
    id: "sg_skin_coat",
    nameKey: "groups.sg_skin_coat",
    symptoms: [
      "sym_blisters_snout_feet",
      "sym_diamond_lesions",
      "sym_ear_necrosis",
      "sym_hair_loss",
      "sym_itching",
      "sym_jaundice",
      "sym_pale_skin",
      "sym_rough_hair",
      "sym_skin_crusts",
      "sym_skin_discoloration",
      "sym_sunburn",
    ],
  },
  {
    id: "sg_digestive_stool",
    nameKey: "groups.sg_digestive_stool",
    symptoms: [
      "sym_bloat",
      "sym_blood_in_stool",
      "sym_bloody_diarrhea",
      "sym_dehydration",
      "sym_diarrhea",
      "sym_loss_of_appetite",
      "sym_rectal_prolapse",
      "sym_vomiting",
      "sym_weight_loss",
    ],
  },
  {
    id: "sg_respiratory",
    nameKey: "groups.sg_respiratory",
    symptoms: [
      "sym_coughing",
      "sym_difficulty_breathing",
      "sym_excessive_salivation",
      "sym_frothing",
      "sym_nasal_discharge",
      "sym_nose_bleeds",
      "sym_sneezing",
      "sym_thumping",
    ],
  },
  {
    id: "sg_behavioral_nervous",
    nameKey: "groups.sg_behavioral_nervous",
    symptoms: [
      "sym_blindness",
      "sym_circling",
      "sym_convulsions",
      "sym_incoordination",
      "sym_lethargy",
      "sym_muscle_stiffness",
      "sym_nervousness",
      "sym_paralysis",
      "sym_seizures",
      "sym_tail_biting",
      "sym_trembling",
      "sym_twitching",
    ],
  },
  {
    id: "sg_reproduction",
    nameKey: "groups.sg_reproduction",
    symptoms: [
      "sym_abortion",
      "sym_enlarged_scrotum",
      "sym_infertility",
      "sym_mummified_piglets",
      "sym_small_litter",
      "sym_swollen_udder",
      "sym_swollen_vulva",
    ],
  },
  {
    id: "sg_general_limbs",
    nameKey: "groups.sg_general_limbs",
    symptoms: [
      "sym_abscesses",
      "sym_anemia",
      "sym_bleeding_orifices",
      "sym_cracked_hooves",
      "sym_fractures",
      "sym_high_fever",
      "sym_lameness",
      "sym_leg_weakness",
      "sym_pale_mucous",
      "sym_red_urine",
      "sym_stunted_growth",
      "sym_sudden_death",
      "sym_swollen_eyelids",
      "sym_swollen_joints",
      "sym_swollen_navel",
      "sym_thirst",
      "sym_watery_diarrhea",
    ],
  },
];

export const DISEASES: DiseaseItem[] = [
    {
      id: "dis_asf",
      nameKey: "diseases.dis_asf.name",
      scientificNameKey: "diseases.dis_asf.scientificName",
      symptomKeys: ["sym_high_fever", "sym_loss_of_appetite", "sym_sudden_death", "sym_skin_discoloration", "sym_lethargy", "sym_vomiting", "sym_diarrhea"],
      descriptionKey: "diseases.dis_asf.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_asf.prevention",
    stages: ["stage_all"],
    isNotifiable: true,
    biosecurityProtocolKey: "bio_proto_asf",
    },
    {
      id: "dis_fmd",
      nameKey: "diseases.dis_fmd.name",
      scientificNameKey: "diseases.dis_fmd.scientificName",
      symptomKeys: ["sym_high_fever", "sym_lameness", "sym_blisters_snout_feet", "sym_loss_of_appetite", "sym_nasal_discharge"],
      descriptionKey: "diseases.dis_fmd.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_fmd.prevention",
    stages: ["stage_all"],
    isNotifiable: true,
    biosecurityProtocolKey: "bio_proto_fmd",
    },
    {
      id: "dis_prrs",
      nameKey: "diseases.dis_prrs.name",
      scientificNameKey: "diseases.dis_prrs.scientificName",
      symptomKeys: ["sym_coughing", "sym_difficulty_breathing", "sym_abortion", "sym_lethargy", "sym_skin_discoloration"],
      descriptionKey: "diseases.dis_prrs.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_prrs.prevention",
    stages: ["stage_all"],
    },
    {
      id: "dis_erysipelas",
      nameKey: "diseases.dis_erysipelas.name",
      scientificNameKey: "diseases.dis_erysipelas.scientificName",
      symptomKeys: ["sym_high_fever", "sym_diamond_lesions", "sym_lameness", "sym_sudden_death"],
      descriptionKey: "diseases.dis_erysipelas.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_erysipelas.prevention",
    stages: ["stage_grower_finisher","stage_breeding_stock"],
    },
    {
      id: "dis_csf",
      nameKey: "diseases.dis_csf.name",
      scientificNameKey: "diseases.dis_csf.scientificName",
      symptomKeys: ["sym_high_fever", "sym_diarrhea", "sym_skin_discoloration", "sym_coughing", "sym_lethargy"],
      descriptionKey: "diseases.dis_csf.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_csf.prevention",
    stages: ["stage_all"],
    isNotifiable: true,
    biosecurityProtocolKey: "bio_proto_csf",
    },
    {
      id: "dis_anthrax",
      nameKey: "diseases.dis_anthrax.name",
      scientificNameKey: "diseases.dis_anthrax.scientificName",
      symptomKeys: ["sym_sudden_death", "sym_high_fever", "sym_difficulty_breathing", "sym_bleeding_orifices"],
      descriptionKey: "diseases.dis_anthrax.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_anthrax.prevention",
    stages: ["stage_all"],
    isNotifiable: true,
    biosecurityProtocolKey: "bio_proto_anthrax",
    },
    {
      id: "dis_brucellosis",
      nameKey: "diseases.dis_brucellosis.name",
      scientificNameKey: "diseases.dis_brucellosis.scientificName",
      symptomKeys: ["sym_abortion", "sym_lameness", "sym_swollen_joints", "sym_lethargy"],
      descriptionKey: "diseases.dis_brucellosis.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_brucellosis.prevention",
    stages: ["stage_breeding_stock"],
    },
    {
      id: "dis_coccidiosis",
      nameKey: "diseases.dis_coccidiosis.name",
      scientificNameKey: "diseases.dis_coccidiosis.scientificName",
      symptomKeys: ["sym_diarrhea", "sym_weight_loss", "sym_lethargy", "sym_loss_of_appetite"],
      descriptionKey: "diseases.dis_coccidiosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_coccidiosis.prevention",
    stages: ["stage_suckling","stage_nursery"],
    },
    {
      id: "dis_pneumonia",
      nameKey: "diseases.dis_pneumonia.name",
      scientificNameKey: "diseases.dis_pneumonia.scientificName",
      symptomKeys: ["sym_coughing", "sym_difficulty_breathing", "sym_weight_loss", "sym_lethargy"],
      descriptionKey: "diseases.dis_pneumonia.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_pneumonia.prevention",
    stages: ["stage_nursery","stage_grower_finisher"],
    },
    {
      id: "dis_salmonellosis",
      nameKey: "diseases.dis_salmonellosis.name",
      scientificNameKey: "diseases.dis_salmonellosis.scientificName",
      symptomKeys: ["sym_diarrhea", "sym_high_fever", "sym_skin_discoloration", "sym_vomiting"],
      descriptionKey: "diseases.dis_salmonellosis.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_salmonellosis.prevention",
    stages: ["stage_all"],
    },
    {
      id: "dis_ppv",
      nameKey: "diseases.dis_ppv.name",
      scientificNameKey: "diseases.dis_ppv.scientificName",
      symptomKeys: ["sym_abortion", "sym_mummified_piglets", "sym_small_litter"],
      descriptionKey: "diseases.dis_ppv.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_ppv.prevention",
    stages: ["stage_breeding_stock"],
    },
    {
      id: "dis_rhinitis",
      nameKey: "diseases.dis_rhinitis.name",
      scientificNameKey: "diseases.dis_rhinitis.scientificName",
      symptomKeys: ["sym_nasal_discharge", "sym_coughing", "sym_sneezing", "sym_weight_loss"],
      descriptionKey: "diseases.dis_rhinitis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_rhinitis.prevention",
    },
    {
      id: "dis_leptospirosis",
      nameKey: "diseases.dis_leptospirosis.name",
      scientificNameKey: "diseases.dis_leptospirosis.scientificName",
      symptomKeys: ["sym_abortion", "sym_high_fever", "sym_loss_of_appetite", "sym_jaundice"],
      descriptionKey: "diseases.dis_leptospirosis.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_leptospirosis.prevention",
    stages: ["stage_breeding_stock","stage_grower_finisher"],
    },
    {
      id: "dis_influenza",
      nameKey: "diseases.dis_influenza.name",
      scientificNameKey: "diseases.dis_influenza.scientificName",
      symptomKeys: ["sym_coughing", "sym_high_fever", "sym_nasal_discharge", "sym_difficulty_breathing"],
      descriptionKey: "diseases.dis_influenza.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_influenza.prevention",
    },
    {
      id: "dis_edema",
      nameKey: "diseases.dis_edema.name",
      scientificNameKey: "diseases.dis_edema.scientificName",
      symptomKeys: ["sym_swollen_eyelids", "sym_seizures", "sym_sudden_death", "sym_loss_of_appetite"],
      descriptionKey: "diseases.dis_edema.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_edema.prevention",
    stages: ["stage_nursery"],
    },
    {
      id: "dis_dysentery",
      nameKey: "diseases.dis_dysentery.name",
      scientificNameKey: "diseases.dis_dysentery.scientificName",
      symptomKeys: ["sym_bloody_diarrhea", "sym_weight_loss", "sym_lethargy"],
      descriptionKey: "diseases.dis_dysentery.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_dysentery.prevention",
    stages: ["stage_grower_finisher","stage_breeding_stock"],
    },
    {
      id: "dis_mange",
      nameKey: "diseases.dis_mange.name",
      scientificNameKey: "diseases.dis_mange.scientificName",
      symptomKeys: ["sym_itching", "sym_hair_loss", "sym_skin_crusts"],
      descriptionKey: "diseases.dis_mange.description",
      severity: "LOW",
      preventionKey: "diseases.dis_mange.prevention",
    },
    {
      id: "dis_anemia",
      nameKey: "diseases.dis_anemia.name",
      scientificNameKey: "diseases.dis_anemia.scientificName",
      symptomKeys: ["sym_pale_skin", "sym_lethargy", "sym_difficulty_breathing"],
      descriptionKey: "diseases.dis_anemia.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_anemia.prevention",
    stages: ["stage_suckling"],
    },
    {
      id: "dis_ulcers",
      nameKey: "diseases.dis_ulcers.name",
      scientificNameKey: "diseases.dis_ulcers.scientificName",
      symptomKeys: ["sym_vomiting", "sym_pale_skin", "sym_weight_loss", "sym_blood_in_stool"],
      descriptionKey: "diseases.dis_ulcers.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_ulcers.prevention",
    stages: ["stage_grower_finisher","stage_breeding_stock"],
    },
    {
      id: "dis_pss",
      nameKey: "diseases.dis_pss.name",
      scientificNameKey: "diseases.dis_pss.scientificName",
      symptomKeys: ["sym_trembling", "sym_muscle_stiffness", "sym_high_fever", "sym_sudden_death"],
      descriptionKey: "diseases.dis_pss.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_pss.prevention",
    stages: ["stage_grower_finisher","stage_breeding_stock"],
    },
    {
      id: "dis_tge",
      nameKey: "diseases.dis_tge.name",
      scientificNameKey: "diseases.dis_tge.scientificName",
      symptomKeys: ["sym_vomiting", "sym_diarrhea", "sym_sudden_death", "sym_dehydration"],
      descriptionKey: "diseases.dis_tge.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_tge.prevention",
    stages: ["stage_suckling","stage_nursery","stage_grower_finisher","stage_breeding_stock"],
    },
    {
      id: "dis_pasteurellosis",
      nameKey: "diseases.dis_pasteurellosis.name",
      scientificNameKey: "diseases.dis_pasteurellosis.scientificName",
      symptomKeys: ["sym_coughing", "sym_high_fever", "sym_difficulty_breathing", "sym_thumping"],
      descriptionKey: "diseases.dis_pasteurellosis.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_pasteurellosis.prevention",
    },
    {
      id: "dis_strep",
      nameKey: "diseases.dis_strep.name",
      scientificNameKey: "diseases.dis_strep.scientificName",
      symptomKeys: ["sym_high_fever", "sym_seizures", "sym_lameness", "sym_incoordination"],
      descriptionKey: "diseases.dis_strep.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_strep.prevention",
    stages: ["stage_suckling","stage_nursery"],
    },
    {
      id: "dis_mycotoxicosis",
      nameKey: "diseases.dis_mycotoxicosis.name",
      scientificNameKey: "diseases.dis_mycotoxicosis.scientificName",
      symptomKeys: ["sym_loss_of_appetite", "sym_vomiting", "sym_abortion", "sym_swollen_vulva"],
      descriptionKey: "diseases.dis_mycotoxicosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_mycotoxicosis.prevention",
    stages: ["stage_breeding_stock","stage_grower_finisher"],
    },
    {
      id: "dis_greasy_pig",
      nameKey: "diseases.dis_greasy_pig.name",
      scientificNameKey: "diseases.dis_greasy_pig.scientificName",
      symptomKeys: ["sym_skin_discoloration", "sym_skin_crusts", "sym_lethargy", "sym_weight_loss"],
      descriptionKey: "diseases.dis_greasy_pig.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_greasy_pig.prevention",
    stages: ["stage_suckling","stage_nursery"],
    },
    {
      id: "dis_pseudorabies",
      nameKey: "diseases.dis_pseudorabies.name",
      scientificNameKey: "diseases.dis_pseudorabies.scientificName",
      symptomKeys: ["sym_seizures", "sym_trembling", "sym_sudden_death", "sym_abortion", "sym_coughing"],
      descriptionKey: "diseases.dis_pseudorabies.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_pseudorabies.prevention",
    stages: ["stage_all"],
    isNotifiable: true,
    biosecurityProtocolKey: "bio_proto_pseudorabies",
    },
    {
      id: "dis_pcv2",
      nameKey: "diseases.dis_pcv2.name",
      scientificNameKey: "diseases.dis_pcv2.scientificName",
      symptomKeys: ["sym_weight_loss", "sym_difficulty_breathing", "sym_diarrhea", "sym_jaundice", "sym_pale_skin"],
      descriptionKey: "diseases.dis_pcv2.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_pcv2.prevention",
    stages: ["stage_nursery","stage_grower_finisher"],
    },
    {
      id: "dis_ped",
      nameKey: "diseases.dis_ped.name",
      scientificNameKey: "diseases.dis_ped.scientificName",
      symptomKeys: ["sym_vomiting", "sym_watery_diarrhea", "sym_dehydration", "sym_sudden_death"],
      descriptionKey: "diseases.dis_ped.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_ped.prevention",
    stages: ["stage_suckling","stage_nursery","stage_grower_finisher","stage_breeding_stock"],
    },
    {
      id: "dis_je",
      nameKey: "diseases.dis_je.name",
      scientificNameKey: "diseases.dis_je.scientificName",
      symptomKeys: ["sym_abortion", "sym_mummified_piglets", "sym_infertility", "sym_trembling"],
      descriptionKey: "diseases.dis_je.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_je.prevention",
    stages: ["stage_breeding_stock"],
    },
    {
      id: "dis_rabies",
      nameKey: "diseases.dis_rabies.name",
      scientificNameKey: "diseases.dis_rabies.scientificName",
      symptomKeys: ["sym_nervousness", "sym_aggression", "sym_excessive_salivation", "sym_paralysis", "sym_sudden_death"],
      descriptionKey: "diseases.dis_rabies.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_rabies.prevention",
    stages: ["stage_all"],
    isNotifiable: true,
    biosecurityProtocolKey: "bio_proto_rabies",
    },
    {
      id: "dis_pox",
      nameKey: "diseases.dis_pox.name",
      scientificNameKey: "diseases.dis_pox.scientificName",
      symptomKeys: ["sym_skin_crusts", "sym_lethargy", "sym_loss_of_appetite"],
      descriptionKey: "diseases.dis_pox.description",
      severity: "LOW",
      preventionKey: "diseases.dis_pox.prevention",
    },
    {
      id: "dis_vs",
      nameKey: "diseases.dis_vs.name",
      scientificNameKey: "diseases.dis_vs.scientificName",
      symptomKeys: ["sym_blisters_snout_feet", "sym_excessive_salivation", "sym_loss_of_appetite"],
      descriptionKey: "diseases.dis_vs.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_vs.prevention",
    stages: ["stage_all"],
    isNotifiable: true,
    biosecurityProtocolKey: "bio_proto_vesicular_stomatitis",
    },
    {
      id: "dis_clostridial",
      nameKey: "diseases.dis_clostridial.name",
      scientificNameKey: "diseases.dis_clostridial.scientificName",
      symptomKeys: ["sym_bloody_diarrhea", "sym_sudden_death", "sym_bloat"],
      descriptionKey: "diseases.dis_clostridial.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_clostridial.prevention",
    stages: ["stage_suckling","stage_nursery"],
    },
    {
      id: "dis_glassers",
      nameKey: "diseases.dis_glassers.name",
      scientificNameKey: "diseases.dis_glassers.scientificName",
      symptomKeys: ["sym_high_fever", "sym_coughing", "sym_lameness", "sym_swollen_joints", "sym_trembling"],
      descriptionKey: "diseases.dis_glassers.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_glassers.prevention",
    stages: ["stage_nursery","stage_grower_finisher"],
    },
    {
      id: "dis_app",
      nameKey: "diseases.dis_app.name",
      scientificNameKey: "diseases.dis_app.scientificName",
      symptomKeys: ["sym_sudden_death", "sym_high_fever", "sym_nose_bleeds", "sym_difficulty_breathing", "sym_coughing"],
      descriptionKey: "diseases.dis_app.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_app.prevention",
    stages: ["stage_grower_finisher","stage_breeding_stock"],
    },
    {
      id: "dis_ileitis",
      nameKey: "diseases.dis_ileitis.name",
      scientificNameKey: "diseases.dis_ileitis.scientificName",
      symptomKeys: ["sym_diarrhea", "sym_blood_in_stool", "sym_weight_loss", "sym_pale_skin"],
      descriptionKey: "diseases.dis_ileitis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_ileitis.prevention",
    stages: ["stage_nursery","stage_grower_finisher"],
    },
    {
      id: "dis_tb",
      nameKey: "diseases.dis_tb.name",
      scientificNameKey: "diseases.dis_tb.scientificName",
      symptomKeys: ["sym_weight_loss", "sym_lethargy", "sym_coughing"],
      descriptionKey: "diseases.dis_tb.description",
      severity: "LOW",
      preventionKey: "diseases.dis_tb.prevention",
    },
    {
      id: "dis_tetanus",
      nameKey: "diseases.dis_tetanus.name",
      scientificNameKey: "diseases.dis_tetanus.scientificName",
      symptomKeys: ["sym_muscle_stiffness", "sym_seizures", "sym_trembling"],
      descriptionKey: "diseases.dis_tetanus.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_tetanus.prevention",
    },
    {
      id: "dis_eperythrozoonosis",
      nameKey: "diseases.dis_eperythrozoonosis.name",
      scientificNameKey: "diseases.dis_eperythrozoonosis.scientificName",
      symptomKeys: ["sym_pale_skin", "sym_jaundice", "sym_high_fever", "sym_infertility", "sym_lethargy", "sym_red_urine"],
      descriptionKey: "diseases.dis_eperythrozoonosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_eperythrozoonosis.prevention",
    },
    {
      id: "dis_ascaris",
      nameKey: "diseases.dis_ascaris.name",
      scientificNameKey: "diseases.dis_ascaris.scientificName",
      symptomKeys: ["sym_coughing", "sym_weight_loss", "sym_stunted_growth", "sym_rough_hair"],
      descriptionKey: "diseases.dis_ascaris.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_ascaris.prevention",
    },
    {
      id: "dis_whipworms",
      nameKey: "diseases.dis_whipworms.name",
      scientificNameKey: "diseases.dis_whipworms.scientificName",
      symptomKeys: ["sym_bloody_diarrhea", "sym_weight_loss", "sym_dehydration"],
      descriptionKey: "diseases.dis_whipworms.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_whipworms.prevention",
    },
    {
      id: "dis_lungworms",
      nameKey: "diseases.dis_lungworms.name",
      scientificNameKey: "diseases.dis_lungworms.scientificName",
      symptomKeys: ["sym_coughing", "sym_thumping", "sym_stunted_growth"],
      descriptionKey: "diseases.dis_lungworms.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_lungworms.prevention",
    },
    {
      id: "dis_kidney_worms",
      nameKey: "diseases.dis_kidney_worms.name",
      scientificNameKey: "diseases.dis_kidney_worms.scientificName",
      symptomKeys: ["sym_weight_loss", "sym_stunted_growth", "sym_leg_weakness"],
      descriptionKey: "diseases.dis_kidney_worms.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_kidney_worms.prevention",
    },
    {
      id: "dis_lice",
      nameKey: "diseases.dis_lice.name",
      scientificNameKey: "diseases.dis_lice.scientificName",
      symptomKeys: ["sym_itching", "sym_rough_hair", "sym_pale_skin", "sym_anemia"],
      descriptionKey: "diseases.dis_lice.description",
      severity: "LOW",
      preventionKey: "diseases.dis_lice.prevention",
    },
    {
      id: "dis_ringworm",
      nameKey: "diseases.dis_ringworm.name",
      scientificNameKey: "diseases.dis_ringworm.scientificName",
      symptomKeys: ["sym_skin_crusts", "sym_itching"],
      descriptionKey: "diseases.dis_ringworm.description",
      severity: "LOW",
      preventionKey: "diseases.dis_ringworm.prevention",
    },
    {
      id: "dis_mulberry_heart",
      nameKey: "diseases.dis_mulberry_heart.name",
      scientificNameKey: "diseases.dis_mulberry_heart.scientificName",
      symptomKeys: ["sym_sudden_death", "sym_difficulty_breathing", "sym_trembling"],
      descriptionKey: "diseases.dis_mulberry_heart.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_mulberry_heart.prevention",
    },
    {
      id: "dis_vit_a",
      nameKey: "diseases.dis_vit_a.name",
      scientificNameKey: "diseases.dis_vit_a.scientificName",
      symptomKeys: ["sym_blindness", "sym_incoordination", "sym_infertility", "sym_trembling"],
      descriptionKey: "diseases.dis_vit_a.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_vit_a.prevention",
    },
    {
      id: "dis_rickets",
      nameKey: "diseases.dis_rickets.name",
      scientificNameKey: "diseases.dis_rickets.scientificName",
      symptomKeys: ["sym_lameness", "sym_swollen_joints", "sym_leg_weakness", "sym_fractures"],
      descriptionKey: "diseases.dis_rickets.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_rickets.prevention",
    },
    {
      id: "dis_salt_poisoning",
      nameKey: "diseases.dis_salt_poisoning.name",
      scientificNameKey: "diseases.dis_salt_poisoning.scientificName",
      symptomKeys: ["sym_seizures", "sym_blindness", "sym_circling", "sym_convulsions", "sym_thirst"],
      descriptionKey: "diseases.dis_salt_poisoning.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_salt_poisoning.prevention",
    },
    {
      id: "dis_heat_stroke",
      nameKey: "diseases.dis_heat_stroke.name",
      scientificNameKey: "diseases.dis_heat_stroke.scientificName",
      symptomKeys: ["sym_high_fever", "sym_difficulty_breathing", "sym_lethargy", "sym_sudden_death"],
      descriptionKey: "diseases.dis_heat_stroke.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_heat_stroke.prevention",
    },
    {
      id: "dis_rectal_prolapse",
      nameKey: "diseases.dis_rectal_prolapse.name",
      scientificNameKey: "diseases.dis_rectal_prolapse.scientificName",
      symptomKeys: ["sym_rectal_prolapse", "sym_blood_in_stool"],
      descriptionKey: "diseases.dis_rectal_prolapse.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_rectal_prolapse.prevention",
    },
    {
      id: "dis_umbilical_hernia",
      nameKey: "diseases.dis_umbilical_hernia.name",
      scientificNameKey: "diseases.dis_umbilical_hernia.scientificName",
      symptomKeys: ["sym_swollen_navel"],
      descriptionKey: "diseases.dis_umbilical_hernia.description",
      severity: "LOW",
      preventionKey: "diseases.dis_umbilical_hernia.prevention",
    },
    {
      id: "dis_scrotal_hernia",
      nameKey: "diseases.dis_scrotal_hernia.name",
      scientificNameKey: "diseases.dis_scrotal_hernia.scientificName",
      symptomKeys: ["sym_enlarged_scrotum"],
      descriptionKey: "diseases.dis_scrotal_hernia.description",
      severity: "LOW",
      preventionKey: "diseases.dis_scrotal_hernia.prevention",
    },
    {
      id: "dis_splayleg",
      nameKey: "diseases.dis_splayleg.name",
      scientificNameKey: "diseases.dis_splayleg.scientificName",
      symptomKeys: ["sym_leg_weakness", "sym_difficulty_breathing", "sym_sudden_death"],
      descriptionKey: "diseases.dis_splayleg.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_splayleg.prevention",
    },
    {
      id: "dis_vulvovaginitis",
      nameKey: "diseases.dis_vulvovaginitis.name",
      scientificNameKey: "diseases.dis_vulvovaginitis.scientificName",
      symptomKeys: ["sym_swollen_vulva", "sym_abortion", "sym_infertility"],
      descriptionKey: "diseases.dis_vulvovaginitis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_vulvovaginitis.prevention",
    },
    {
      id: "dis_seneca",
      nameKey: "diseases.dis_seneca.name",
      scientificNameKey: "diseases.dis_seneca.scientificName",
      symptomKeys: ["sym_blisters_snout_feet", "sym_lameness", "sym_sudden_death"],
      descriptionKey: "diseases.dis_seneca.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_seneca.prevention",
    stages: ["stage_all"],
    isNotifiable: true,
    biosecurityProtocolKey: "bio_proto_senecavirus",
    },
    {
      id: "dis_deltacoronavirus",
      nameKey: "diseases.dis_deltacoronavirus.name",
      scientificNameKey: "diseases.dis_deltacoronavirus.scientificName",
      symptomKeys: ["sym_watery_diarrhea", "sym_vomiting", "sym_dehydration"],
      descriptionKey: "diseases.dis_deltacoronavirus.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_deltacoronavirus.prevention",
    stages: ["stage_suckling","stage_nursery"],
    },
    {
      id: "dis_rotavirus",
      nameKey: "diseases.dis_rotavirus.name",
      scientificNameKey: "diseases.dis_rotavirus.scientificName",
      symptomKeys: ["sym_diarrhea", "sym_vomiting", "sym_weight_loss"],
      descriptionKey: "diseases.dis_rotavirus.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_rotavirus.prevention",
    stages: ["stage_suckling","stage_nursery"],
    },
    {
      id: "dis_teschen",
      nameKey: "diseases.dis_teschen.name",
      scientificNameKey: "diseases.dis_teschen.scientificName",
      symptomKeys: ["sym_paralysis", "sym_incoordination", "sym_seizures", "sym_trembling"],
      descriptionKey: "diseases.dis_teschen.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_teschen.prevention",
    },
    {
      id: "dis_vesicular",
      nameKey: "diseases.dis_vesicular.name",
      scientificNameKey: "diseases.dis_vesicular.scientificName",
      symptomKeys: ["sym_blisters_snout_feet", "sym_lameness", "sym_high_fever"],
      descriptionKey: "diseases.dis_vesicular.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_vesicular.prevention",
    stages: ["stage_all"],
    isNotifiable: true,
    biosecurityProtocolKey: "bio_proto_svd",
    },
    {
      id: "dis_melioidosis",
      nameKey: "diseases.dis_melioidosis.name",
      scientificNameKey: "diseases.dis_melioidosis.scientificName",
      symptomKeys: ["sym_high_fever", "sym_coughing", "sym_lameness", "sym_abscesses"],
      descriptionKey: "diseases.dis_melioidosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_melioidosis.prevention",
    },
    {
      id: "dis_trypanosomiasis",
      nameKey: "diseases.dis_trypanosomiasis.name",
      scientificNameKey: "diseases.dis_trypanosomiasis.scientificName",
      symptomKeys: ["sym_high_fever", "sym_anemia", "sym_weight_loss", "sym_lethargy", "sym_abortion"],
      descriptionKey: "diseases.dis_trypanosomiasis.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_trypanosomiasis.prevention",
    },
    {
      id: "dis_cysticercosis",
      nameKey: "diseases.dis_cysticercosis.name",
      scientificNameKey: "diseases.dis_cysticercosis.scientificName",
      symptomKeys: ["sym_muscle_stiffness", "sym_seizures"],
      descriptionKey: "diseases.dis_cysticercosis.description",
      severity: "LOW",
      preventionKey: "diseases.dis_cysticercosis.prevention",
    },
    {
      id: "dis_toxoplasmosis",
      nameKey: "diseases.dis_toxoplasmosis.name",
      scientificNameKey: "diseases.dis_toxoplasmosis.scientificName",
      symptomKeys: ["sym_abortion", "sym_high_fever", "sym_difficulty_breathing", "sym_lethargy"],
      descriptionKey: "diseases.dis_toxoplasmosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_toxoplasmosis.prevention",
    stages: ["stage_breeding_stock"],
    },
    {
      id: "dis_listeriosis",
      nameKey: "diseases.dis_listeriosis.name",
      scientificNameKey: "diseases.dis_listeriosis.scientificName",
      symptomKeys: ["sym_seizures", "sym_circling", "sym_abortion", "sym_high_fever"],
      descriptionKey: "diseases.dis_listeriosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_listeriosis.prevention",
    },
    {
      id: "dis_ear_necrosis",
      nameKey: "diseases.dis_ear_necrosis.name",
      scientificNameKey: "diseases.dis_ear_necrosis.scientificName",
      symptomKeys: ["sym_ear_necrosis", "sym_skin_discoloration", "sym_lethargy"],
      descriptionKey: "diseases.dis_ear_necrosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_ear_necrosis.prevention",
    stages: ["stage_nursery","stage_grower_finisher"],
    },
    {
      id: "dis_sunburn",
      nameKey: "diseases.dis_sunburn.name",
      scientificNameKey: "diseases.dis_sunburn.scientificName",
      symptomKeys: ["sym_sunburn", "sym_skin_discoloration", "sym_lethargy"],
      descriptionKey: "diseases.dis_sunburn.description",
      severity: "LOW",
      preventionKey: "diseases.dis_sunburn.prevention",
    },
    {
      id: "dis_tail_biting",
      nameKey: "diseases.dis_tail_biting.name",
      scientificNameKey: "diseases.dis_tail_biting.scientificName",
      symptomKeys: ["sym_tail_biting", "sym_blood_in_stool", "sym_lameness"],
      descriptionKey: "diseases.dis_tail_biting.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_tail_biting.prevention",
    stages: ["stage_nursery","stage_grower_finisher"],
    },
    {
      id: "dis_navel_ill",
      nameKey: "diseases.dis_navel_ill.name",
      scientificNameKey: "diseases.dis_navel_ill.scientificName",
      symptomKeys: ["sym_swollen_navel", "sym_high_fever", "sym_lameness"],
      descriptionKey: "diseases.dis_navel_ill.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_navel_ill.prevention",
    stages: ["stage_suckling"],
    },
    {
      id: "dis_iron_toxicity",
      nameKey: "diseases.dis_iron_toxicity.name",
      scientificNameKey: "diseases.dis_iron_toxicity.scientificName",
      symptomKeys: ["sym_sudden_death", "sym_difficulty_breathing", "sym_muscle_stiffness"],
      descriptionKey: "diseases.dis_iron_toxicity.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_iron_toxicity.prevention",
    stages: ["stage_suckling"],
    },
    {
      id: "dis_aflatoxicosis",
      nameKey: "diseases.dis_aflatoxicosis.name",
      scientificNameKey: "diseases.dis_aflatoxicosis.scientificName",
      symptomKeys: ["sym_loss_of_appetite", "sym_weight_loss", "sym_jaundice", "sym_lethargy", "sym_sudden_death"],
      descriptionKey: "diseases.dis_aflatoxicosis.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_aflatoxicosis.prevention",
    },
    {
      id: "dis_parakeratosis",
      nameKey: "diseases.dis_parakeratosis.name",
      scientificNameKey: "diseases.dis_parakeratosis.scientificName",
      symptomKeys: ["sym_skin_crusts", "sym_rough_hair", "sym_stunted_growth"],
      descriptionKey: "diseases.dis_parakeratosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_parakeratosis.prevention",
    stages: ["stage_nursery","stage_grower_finisher"],
    },
    {
      id: "dis_biotin_deficiency",
      nameKey: "diseases.dis_biotin_deficiency.name",
      scientificNameKey: "diseases.dis_biotin_deficiency.scientificName",
      symptomKeys: ["sym_lameness", "sym_hair_loss", "sym_leg_weakness", "sym_cracked_hooves"],
      descriptionKey: "diseases.dis_biotin_deficiency.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_biotin_deficiency.prevention",
    },
    {
      id: "dis_gossypol_toxicity",
      nameKey: "diseases.dis_gossypol_toxicity.name",
      scientificNameKey: "diseases.dis_gossypol_toxicity.scientificName",
      symptomKeys: ["sym_difficulty_breathing", "sym_thumping", "sym_loss_of_appetite", "sym_sudden_death"],
      descriptionKey: "diseases.dis_gossypol_toxicity.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_gossypol_toxicity.prevention",
    },
    {
      id: "dis_cassava_poisoning",
      nameKey: "diseases.dis_cassava_poisoning.name",
      scientificNameKey: "diseases.dis_cassava_poisoning.scientificName",
      symptomKeys: ["sym_difficulty_breathing", "sym_incoordination", "sym_sudden_death", "sym_lethargy"],
      descriptionKey: "diseases.dis_cassava_poisoning.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_cassava_poisoning.prevention",
    },
    {
      id: "dis_sweet_potato_toxicity",
      nameKey: "diseases.dis_sweet_potato_toxicity.name",
      scientificNameKey: "diseases.dis_sweet_potato_toxicity.scientificName",
      symptomKeys: ["sym_difficulty_breathing", "sym_thumping", "sym_frothing"],
      descriptionKey: "diseases.dis_sweet_potato_toxicity.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_sweet_potato_toxicity.prevention",
    },
    {
      id: "dis_mma",
      nameKey: "diseases.dis_mma.name",
      scientificNameKey: "diseases.dis_mma.scientificName",
      symptomKeys: ["sym_high_fever", "sym_lethargy", "sym_loss_of_appetite", "sym_swollen_udder"],
      descriptionKey: "diseases.dis_mma.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_mma.prevention",
    stages: ["stage_breeding_stock"],
    },
    {
      id: "dis_pwd",
      nameKey: "diseases.dis_pwd.name",
      scientificNameKey: "diseases.dis_pwd.scientificName",
      symptomKeys: ["sym_diarrhea", "sym_dehydration", "sym_loss_of_appetite", "sym_weight_loss"],
      descriptionKey: "diseases.dis_pwd.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_pwd.prevention",
    stages: ["stage_nursery"],
    },
    {
      id: "dis_trichinellosis",
      nameKey: "diseases.dis_trichinellosis.name",
      scientificNameKey: "diseases.dis_trichinellosis.scientificName",
      symptomKeys: ["sym_muscle_stiffness", "sym_lethargy", "sym_incoordination"],
      descriptionKey: "diseases.dis_trichinellosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_trichinellosis.prevention",
    },
    {
      id: "dis_hydatid_disease",
      nameKey: "diseases.dis_hydatid_disease.name",
      scientificNameKey: "diseases.dis_hydatid_disease.scientificName",
      symptomKeys: ["sym_weight_loss", "sym_stunted_growth", "sym_lethargy"],
      descriptionKey: "diseases.dis_hydatid_disease.description",
      severity: "LOW",
      preventionKey: "diseases.dis_hydatid_disease.prevention",
    },
    {
      id: "dis_phe",
      nameKey: "diseases.dis_phe.name",
      scientificNameKey: "diseases.dis_phe.scientificName",
      symptomKeys: ["sym_bloody_diarrhea", "sym_pale_skin", "sym_sudden_death"],
      descriptionKey: "diseases.dis_phe.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_phe.prevention",
    stages: ["stage_grower_finisher","stage_breeding_stock"],
    },
    {
      id: "dis_mycoplasma_arthritis",
      nameKey: "diseases.dis_mycoplasma_arthritis.name",
      scientificNameKey: "diseases.dis_mycoplasma_arthritis.scientificName",
      symptomKeys: ["sym_lameness", "sym_swollen_joints", "sym_leg_weakness"],
      descriptionKey: "diseases.dis_mycoplasma_arthritis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_mycoplasma_arthritis.prevention",
    },
    {
      id: "dis_foot_rot",
      nameKey: "diseases.dis_foot_rot.name",
      scientificNameKey: "diseases.dis_foot_rot.scientificName",
      symptomKeys: ["sym_lameness", "sym_lethargy", "sym_loss_of_appetite", "sym_cracked_hooves"],
      descriptionKey: "diseases.dis_foot_rot.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_foot_rot.prevention",
    },
    {
      id: "dis_babesiosis",
      nameKey: "diseases.dis_babesiosis.name",
      scientificNameKey: "diseases.dis_babesiosis.scientificName",
      symptomKeys: ["sym_high_fever", "sym_jaundice", "sym_pale_skin", "sym_abortion", "sym_lethargy", "sym_red_urine"],
      descriptionKey: "diseases.dis_babesiosis.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_babesiosis.prevention",
    },
    {
      id: "dis_anaplasmosis",
      nameKey: "diseases.dis_anaplasmosis.name",
      scientificNameKey: "diseases.dis_anaplasmosis.scientificName",
      symptomKeys: ["sym_high_fever", "sym_pale_skin", "sym_jaundice", "sym_lethargy"],
      descriptionKey: "diseases.dis_anaplasmosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_anaplasmosis.prevention",
    },
    {
      id: "dis_sow_hysteria",
      nameKey: "diseases.dis_sow_hysteria.name",
      scientificNameKey: "diseases.dis_sow_hysteria.scientificName",
      symptomKeys: ["sym_nervousness", "sym_lethargy"],
      descriptionKey: "diseases.dis_sow_hysteria.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_sow_hysteria.prevention",
    },
    {
      id: "dis_thorny_headed_worm",
      nameKey: "diseases.dis_thorny_headed_worm.name",
      scientificNameKey: "diseases.dis_thorny_headed_worm.scientificName",
      symptomKeys: ["sym_diarrhea", "sym_weight_loss", "sym_stunted_growth", "sym_sudden_death"],
      descriptionKey: "diseases.dis_thorny_headed_worm.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_thorny_headed_worm.prevention",
    },
    {
      id: "dis_strongyloidiasis",
      nameKey: "diseases.dis_strongyloidiasis.name",
      scientificNameKey: "diseases.dis_strongyloidiasis.scientificName",
      symptomKeys: ["sym_diarrhea", "sym_dehydration", "sym_stunted_growth", "sym_sudden_death"],
      descriptionKey: "diseases.dis_strongyloidiasis.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_strongyloidiasis.prevention",
    },
    {
      id: "dis_hyostrongylosis",
      nameKey: "diseases.dis_hyostrongylosis.name",
      scientificNameKey: "diseases.dis_hyostrongylosis.scientificName",
      symptomKeys: ["sym_weight_loss", "sym_pale_skin", "sym_rough_hair", "sym_loss_of_appetite"],
      descriptionKey: "diseases.dis_hyostrongylosis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_hyostrongylosis.prevention",
    },
    {
      id: "dis_oesophagostomiasis",
      nameKey: "diseases.dis_oesophagostomiasis.name",
      scientificNameKey: "diseases.dis_oesophagostomiasis.scientificName",
      symptomKeys: ["sym_weight_loss", "sym_diarrhea", "sym_rough_hair"],
      descriptionKey: "diseases.dis_oesophagostomiasis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_oesophagostomiasis.prevention",
    },
    {
      id: "dis_fascioliasis",
      nameKey: "diseases.dis_fascioliasis.name",
      scientificNameKey: "diseases.dis_fascioliasis.scientificName",
      symptomKeys: ["sym_weight_loss", "sym_lethargy", "sym_stunted_growth", "sym_jaundice"],
      descriptionKey: "diseases.dis_fascioliasis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_fascioliasis.prevention",
    },
    {
      id: "dis_emcv",
      nameKey: "diseases.dis_emcv.name",
      scientificNameKey: "diseases.dis_emcv.scientificName",
      symptomKeys: ["sym_sudden_death", "sym_difficulty_breathing", "sym_abortion", "sym_trembling"],
      descriptionKey: "diseases.dis_emcv.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_emcv.prevention",
    },
    {
      id: "dis_demodectic_mange",
      nameKey: "diseases.dis_demodectic_mange.name",
      scientificNameKey: "diseases.dis_demodectic_mange.scientificName",
      symptomKeys: ["sym_skin_crusts", "sym_itching", "sym_hair_loss"],
      descriptionKey: "diseases.dis_demodectic_mange.description",
      severity: "LOW",
      preventionKey: "diseases.dis_demodectic_mange.prevention",
    },
    {
      id: "dis_pityriasis_rosea",
      nameKey: "diseases.dis_pityriasis_rosea.name",
      scientificNameKey: "diseases.dis_pityriasis_rosea.scientificName",
      symptomKeys: ["sym_skin_crusts", "sym_rough_hair"],
      descriptionKey: "diseases.dis_pityriasis_rosea.description",
      severity: "LOW",
      preventionKey: "diseases.dis_pityriasis_rosea.prevention",
    },
    {
      id: "dis_photosensitization",
      nameKey: "diseases.dis_photosensitization.name",
      scientificNameKey: "diseases.dis_photosensitization.scientificName",
      symptomKeys: ["sym_skin_discoloration", "sym_sunburn", "sym_skin_crusts"],
      descriptionKey: "diseases.dis_photosensitization.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_photosensitization.prevention",
    },
    {
      id: "dis_shoulder_ulcers",
      nameKey: "diseases.dis_shoulder_ulcers.name",
      scientificNameKey: "diseases.dis_shoulder_ulcers.scientificName",
      symptomKeys: ["sym_lameness", "sym_pale_skin"],
      descriptionKey: "diseases.dis_shoulder_ulcers.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_shoulder_ulcers.prevention",
    stages: ["stage_breeding_stock"],
    },
    {
      id: "dis_ear_biting",
      nameKey: "diseases.dis_ear_biting.name",
      scientificNameKey: "diseases.dis_ear_biting.scientificName",
      symptomKeys: ["sym_ear_necrosis", "sym_bleeding_orifices"],
      descriptionKey: "diseases.dis_ear_biting.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_ear_biting.prevention",
    stages: ["stage_nursery","stage_grower_finisher"],
    },
    {
      id: "dis_gastric_torsion",
      nameKey: "diseases.dis_gastric_torsion.name",
      scientificNameKey: "diseases.dis_gastric_torsion.scientificName",
      symptomKeys: ["sym_bloat", "sym_sudden_death", "sym_vomiting"],
      descriptionKey: "diseases.dis_gastric_torsion.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_gastric_torsion.prevention",
    stages: ["stage_grower_finisher","stage_breeding_stock"],
    },
    {
      id: "dis_c_difficile",
      nameKey: "diseases.dis_c_difficile.name",
      scientificNameKey: "diseases.dis_c_difficile.scientificName",
      symptomKeys: ["sym_diarrhea", "sym_dehydration", "sym_lethargy"],
      descriptionKey: "diseases.dis_c_difficile.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_c_difficile.prevention",
    stages: ["stage_suckling"],
    },
    {
      id: "dis_cold_stress",
      nameKey: "diseases.dis_cold_stress.name",
      scientificNameKey: "diseases.dis_cold_stress.scientificName",
      symptomKeys: ["sym_trembling", "sym_lethargy", "sym_sudden_death"],
      descriptionKey: "diseases.dis_cold_stress.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_cold_stress.prevention",
    stages: ["stage_suckling","stage_nursery"],
    },
    {
      id: "dis_necrotic_enteritis",
      nameKey: "diseases.dis_necrotic_enteritis.name",
      scientificNameKey: "diseases.dis_necrotic_enteritis.scientificName",
      symptomKeys: ["sym_bloody_diarrhea", "sym_sudden_death", "sym_dehydration"],
      descriptionKey: "diseases.dis_necrotic_enteritis.description",
      severity: "CRITICAL",
      preventionKey: "diseases.dis_necrotic_enteritis.prevention",
    stages: ["stage_suckling"],
    },
    {
      id: "dis_navel_bleeding",
      nameKey: "diseases.dis_navel_bleeding.name",
      scientificNameKey: "diseases.dis_navel_bleeding.scientificName",
      symptomKeys: ["sym_bleeding_orifices", "sym_pale_skin", "sym_sudden_death"],
      descriptionKey: "diseases.dis_navel_bleeding.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_navel_bleeding.prevention",
    stages: ["stage_suckling"],
    },
    {
      id: "dis_spirochetal_colitis",
      nameKey: "diseases.dis_spirochetal_colitis.name",
      scientificNameKey: "diseases.dis_spirochetal_colitis.scientificName",
      symptomKeys: ["sym_diarrhea", "sym_weight_loss", "sym_stunted_growth"],
      descriptionKey: "diseases.dis_spirochetal_colitis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_spirochetal_colitis.prevention",
    stages: ["stage_grower_finisher"],
    },
    {
      id: "dis_salmonella_septicemia",
      nameKey: "diseases.dis_salmonella_septicemia.name",
      scientificNameKey: "diseases.dis_salmonella_septicemia.scientificName",
      symptomKeys: ["sym_high_fever", "sym_skin_discoloration", "sym_difficulty_breathing", "sym_sudden_death"],
      descriptionKey: "diseases.dis_salmonella_septicemia.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_salmonella_septicemia.prevention",
    stages: ["stage_nursery","stage_grower_finisher"],
    },
    {
      id: "dis_prdc",
      nameKey: "diseases.dis_prdc.name",
      scientificNameKey: "diseases.dis_prdc.scientificName",
      symptomKeys: ["sym_coughing", "sym_difficulty_breathing", "sym_nasal_discharge", "sym_stunted_growth"],
      descriptionKey: "diseases.dis_prdc.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_prdc.prevention",
    stages: ["stage_grower_finisher"],
    },
    {
      id: "dis_ergotism",
      nameKey: "diseases.dis_ergotism.name",
      scientificNameKey: "diseases.dis_ergotism.scientificName",
      symptomKeys: ["sym_lameness", "sym_skin_crusts", "sym_abortion", "sym_infertility"],
      descriptionKey: "diseases.dis_ergotism.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_ergotism.prevention",
    stages: ["stage_breeding_stock","stage_grower_finisher"],
    },
    {
      id: "dis_bvdv_pig",
      nameKey: "diseases.dis_bvdv_pig.name",
      scientificNameKey: "diseases.dis_bvdv_pig.scientificName",
      symptomKeys: ["sym_abortion", "sym_mummified_piglets", "sym_small_litter"],
      descriptionKey: "diseases.dis_bvdv_pig.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_bvdv_pig.prevention",
    stages: ["stage_breeding_stock"],
    },
    {
      id: "dis_endocarditis",
      nameKey: "diseases.dis_endocarditis.name",
      scientificNameKey: "diseases.dis_endocarditis.scientificName",
      symptomKeys: ["sym_sudden_death", "sym_difficulty_breathing", "sym_lethargy", "sym_lameness"],
      descriptionKey: "diseases.dis_endocarditis.description",
      severity: "HIGH",
      preventionKey: "diseases.dis_endocarditis.prevention",
    stages: ["stage_grower_finisher"],
    },
    {
      id: "dis_polyserositis",
      nameKey: "diseases.dis_polyserositis.name",
      scientificNameKey: "diseases.dis_polyserositis.scientificName",
      symptomKeys: ["sym_high_fever", "sym_difficulty_breathing", "sym_swollen_joints", "sym_lameness"],
      descriptionKey: "diseases.dis_polyserositis.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_polyserositis.prevention",
    stages: ["stage_nursery","stage_grower_finisher"],
    },
    {
      id: "dis_congenital_tremor",
      nameKey: "diseases.dis_congenital_tremor.name",
      scientificNameKey: "diseases.dis_congenital_tremor.scientificName",
      symptomKeys: ["sym_trembling", "sym_incoordination", "sym_sudden_death"],
      descriptionKey: "diseases.dis_congenital_tremor.description",
      severity: "MODERATE",
      preventionKey: "diseases.dis_congenital_tremor.prevention",
    stages: ["stage_suckling"],
    },
  ];

  


export interface DiagnosisMatchResult {
  disease: DiseaseItem;
  matches: number;
  matchPercent: number;
  totalSymptoms: number;
  matchedWeight: number;
  totalWeight: number;
  matchedPathognomonic: string[];
  isNotifiableAlert: boolean;
}

export function diagnoseSwineDiseases(
  selectedSymptoms: Set<string>,
  stageFilter: PigStage = "stage_all"
): DiagnosisMatchResult[] {
  if (selectedSymptoms.size === 0) return [];

  const results: DiagnosisMatchResult[] = [];

  for (const disease of DISEASES) {
    if (stageFilter !== "stage_all" && disease.stages && disease.stages.length > 0) {
      const matchStage = disease.stages.includes("stage_all") || disease.stages.includes(stageFilter);
      if (!matchStage) continue;
    }

    const matchedSymptoms = disease.symptomKeys.filter((sk) => selectedSymptoms.has(sk));
    if (matchedSymptoms.length === 0) continue;

    const matchedWeight = matchedSymptoms.reduce((sum, sk) => sum + getSymptomWeight(sk), 0);
    const totalWeight = Math.max(1.0, disease.symptomKeys.reduce((sum, sk) => sum + getSymptomWeight(sk), 0));
    const matchPercent = Math.min(100, Math.max(1, Math.round((matchedWeight / totalWeight) * 100)));

    const matchedPathognomonic = matchedSymptoms.filter((sk) => isPathognomonic(sk));
    const isNotifiableAlert = Boolean(
      disease.isNotifiable &&
      (matchPercent >= 35 || matchedPathognomonic.length > 0 || matchedSymptoms.length >= 2)
    );

    results.push({
      disease,
      matches: matchedSymptoms.length,
      matchPercent,
      totalSymptoms: disease.symptomKeys.length,
      matchedWeight,
      totalWeight,
      matchedPathognomonic,
      isNotifiableAlert,
    });
  }

  results.sort((a, b) => {
    if (a.isNotifiableAlert !== b.isNotifiableAlert) {
      return a.isNotifiableAlert ? -1 : 1;
    }
    if (b.matchPercent !== a.matchPercent) {
      return b.matchPercent - a.matchPercent;
    }
    return b.matchedWeight - a.matchedWeight;
  });

  return results;
}
