"use client";

import React from "react";
import Link from "next/link";
import { useDevice } from "@/context/DeviceContext";
import NavbarDropdown from "@/components/NavbarDropdown";

export default function TermsOfServicePage() {
  const { isMobile } = useDevice();

  const sections = [
    {
      title: "1. Acceptance of Terms",
      content: "By accessing and using SmartSwine app, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service."
    },
    {
      title: "2. Description of Service",
      content: "\"SmartSwine\" provides farm management tools including, but not limited to:\n• Herd tracking and health data.\n• Financial record keeping.\n• Human Resource management.\n• AI-assisted diagnostic suggestions.\n• Market access information."
    },
    {
      title: "3. Data Privacy & Cloud Backup",
      content: "You retain ownership of the data you input (herd data, financials, e.t.c.). \nYour farm data is stored securely using Google Firebase, while we strive to protect your data, we cannot guarantee absolute security. \nBy enabling Cloud Backup, you consent to the storage and synchronization of your data across your devices. \nWe do not sell your personal or farm data to third parties.\nYou are responsible for the accuracy of the data entered. Incorrect data in the \"Feed\" or \"Financials\" modules may result in incorrect calculations."
    },
    {
      title: "4. No Medical or Veterinary Advice (Critical Disclaimer)",
      content: "The \"Feed Calculator\", \"Feed Formulator\", \"Symptoms Analyzer\" and \"Disease Finder\" features are for educational and informational purposes only.\n• The AI results are generated by algorithms and are not a substitute for professional veterinary advice, diagnosis, or treatment.\n• The User agrees to consult a licensed veterinarian before making any feeding and medical decisions regarding livestock.\n• The App Owner is not liable for any livestock loss or damages resulting from the use of the app and its features."
    },
    {
      title: "5. User Responsibilities",
      content: "Users are responsible for maintaining the confidentiality of their account credentials. You are responsible for all activities that occur under your account."
    },
    {
      title: "6. Prohibited Conduct",
      content: "Users agree not to:\n• Use the app for any illegal purposes.\n• Attempt to reverse engineer the application.\n• Input fraudulent financial data for the purpose of deceiving third parties."
    },
    {
      title: "7. Service Availability",
      content: "We strive for 99% uptime but do not guarantee uninterrupted access to the service. Data backups are provided as a convenience; however, users are encouraged to maintain their own records."
    },
    {
      title: "8. Limitation of Liability",
      content: "SmartSwine app is provided \"as is.\" To the maximum extent permitted by law, its developers shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service, including livestock loss or financial discrepancies."
    },
    {
      title: "9. Financial Data",
      content: "The \"Financials\" module is a tracking tool and does not constitute professional accounting or tax advice. Users are encouraged to export their data for review by certified accountants."
    },
    {
      title: "10. Changes to Terms",
      content: "We reserve the right to modify these terms at any time. Continued use of the app constitutes acceptance of the new terms."
    },
    {
      title: "11. Contact Information",
      content: "For support or legal inquiries, please contact the developer through the app's profile settings or at bibiniitech@gmail.com."
    }
  ];

  return (
    <div className="relative min-h-screen bg-white text-zinc-900 flex flex-col font-sans overflow-hidden">
      {/* Watermark Logo Background */}
      {!isMobile && (
        <div className="fixed inset-0 z-0 flex items-center justify-center opacity-[0.15] pointer-events-none select-none">
          <img
            src="/app_logo.png"
            alt="Watermark Background Logo"
            className="w-full max-w-[1100px] max-h-[85vh] object-contain"
          />
        </div>
      )}

      <div className="relative z-10 flex flex-col min-h-screen">
        {/* Header */}
        {!isMobile && (
          <header className="border-b border-zinc-200 bg-white/80 backdrop-blur-md sticky top-0 z-50">
            <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
              <Link href="/dashboard" className="flex items-center gap-3 hover:opacity-80 transition-opacity cursor-pointer">
                <img src="/app_logo.png" alt="SmartSwine Logo" className="h-8 w-8 object-contain rounded-md" />
                <span className="font-bold text-sm bg-gradient-to-r from-emerald-700 via-emerald-600 to-green-500 bg-clip-text text-transparent mr-2 inline-block">
                  SmartSwine
                </span>
              </Link>

              <div className="flex items-center gap-2">
                <NavbarDropdown />
              </div>
            </div>
          </header>
        )}

        {/* Content Body */}
        <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
          <div className="text-center space-y-4">
            <h1 className="text-4xl font-extrabold text-zinc-900 tracking-tight">Terms of Service</h1>
            <p className="text-sm text-zinc-500 font-medium">Last Updated: April 2026</p>
          </div>

          <div className="space-y-10">
            {sections.map((section, index) => (
              <section key={index} className="space-y-3">
                <h2 className="text-xl font-bold text-emerald-700">{section.title}</h2>
                <div className="text-zinc-600 leading-relaxed whitespace-pre-line text-lg">
                  {section.content}
                </div>
              </section>
            ))}
          </div>

          <div className="pt-12 border-t border-zinc-100 text-center">
            <p className="text-lg font-bold text-emerald-600">
              Contact Support: <a href="mailto:bibiniitech@gmail.com" className="hover:underline">bibiniitech@gmail.com</a>
            </p>
          </div>

          <div className="h-20" />
        </main>
      </div>
    </div>
  );
}
